### ISSUE TITLE
Parse error: syntax error, unexpected 'public' (T_PUBLIC)

### ISSUE THREAD

**Issue by Camilo517** [Prospress/woocommerce-subscriptions-cancel-after-retry#2]
Hello, I have this error and I can not activate the plugin

Parse error: syntax error, unexpected 'public' (T_PUBLIC), expecting end of file in /var/www/vhosts/web.com/httpdocs/wp-content/plugins/woocommerce-subscriptions-cancel-after-retry-master/woocommerce-subscriptions-cancel-after-retry.php on line 55

**Comment by thenbrent** [comment]
Hi @Camilo517. I've fixed that up with https://github.com/Prospress/woocommerce-subscriptions-cancel-after-retry/commit/6c0ff0c1df6f3a458e07973b3c00201e970e1e59.

This code is still technically pre-release / alpha. Use at your own risk. It's going through audit for a live site in the next day or so though.
